/**
 * Runs every persona through the app for months and writes a report of what
 * the app showed and how often it was wrong. `npm run sim`
 */
import { writeFileSync } from 'node:fs'
import { PERSONAS } from '../src/sim/personas'
import { summarize, type Engine, type Summary } from '../src/sim/run'

const SEEDS = [1, 2, 3, 4, 5]
const mean = (xs: (number | null)[]) => {
  const v = xs.filter((x): x is number => x !== null)
  return v.length ? v.reduce((a, b) => a + b, 0) / v.length : null
}
const f = (x: number | null, d = 0) => (x === null ? '—' : x.toFixed(d))
const pct = (x: number | null) => (x === null ? '—' : `${Math.round(x * 100)}%`)

function row(engine: Engine) {
  const lines: string[] = []
  lines.push('| persona | days | first insight (day) | first factor claim | first true claim | insights @7/14/30/60 | claim-days false | distinct false claims | Today card empty (days after 3) | distinct cards | risk flags | risk lift | lessons (distinct/days) | rate gap @90 |')
  lines.push('|---|---|---|---|---|---|---|---|---|---|---|---|---|---|')
  for (const p of PERSONAS) {
    const ss: Summary[] = summarize(p, engine, SEEDS)
    const at = (d: number) => f(mean(ss.map((s) => s.insightsAt[d] ?? null)), 1)
    const claimDays = ss.reduce((a, s) => a + s.claimDays, 0)
    const falseDays = ss.reduce((a, s) => a + s.falseClaimDays, 0)
    const distinctFalse = new Set(ss.flatMap((s) => s.distinctFalse))
    lines.push(
      `| ${p.name} | ${p.days} | ${f(mean(ss.map((s) => s.firstFact)), 1)} | ${f(mean(ss.map((s) => s.firstClaim)), 1)} | ${f(mean(ss.map((s) => s.firstTrueClaim)), 1)} | ${at(7)} / ${at(14)} / ${at(30)} / ${at(60)} | ${claimDays ? pct(falseDays / claimDays) : '—'} (${claimDays}) | ${distinctFalse.size ? [...distinctFalse].slice(0, 4).join(', ') : 'none'} | ${f(mean(ss.map((s) => s.emptyCardDays)), 1)} | ${f(mean(ss.map((s) => s.distinctCards)), 1)} | ${f(mean(ss.map((s) => s.riskDays)), 1)} | ${f(mean(ss.map((s) => s.riskLift)), 2)} | ${f(mean(ss.map((s) => s.lessonsDistinct)), 1)}/${f(mean(ss.map((s) => s.lessonDays)), 1)} | ${f(mean(ss.map((s) => s.rateGap90)), 3)} |`,
    )
  }
  return lines.join('\n')
}

const out = [
  '# Simulation report',
  '',
  `Generated by \`npm run sim\`. Each persona (src/sim/personas.ts) is a synthetic user with known ground truth, run through the app's real logic day by day, ${SEEDS.length} random seeds each; numbers are averages across seeds.`,
  '',
  '- **first insight / claim**: first day the app has anything to say / says something about a specific tracked item.',
  '- **claim-days false**: share of (day × claim) pairs where the claim contradicts the persona\'s ground truth (the item has no effect, or the direction is wrong). Claims about items that move with a real cause (e.g. sleep before midnight vs short nights) count as true associations.',
  '- **risk lift**: setback rate on days the risk window was flagged ÷ rate on other days (after day 30). Above 1 means the flag is informative.',
  '- **rate gap @90**: reported 30-day rate minus the true one at day 90. Positive means the app looks rosier than reality.',
  '',
  '## Before: setback factors only',
  '',
  row('baseline'),
  '',
  '## After: full insight engine',
  '',
  row('current'),
  '',
].join('\n')

writeFileSync('docs/simulation-report.md', out)
console.log(out)
